# Generated by Django 5.0 on 2025-07-28 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
